image: node:16.14.0

pipelines:
  branches:
    dev:
      - step:
          name: Setup & Build
          script:
            - npm install
            - npm run build
          artifacts:
            - dist/**

      - step:
          name: Deploy to Firebase
          deployment: test
          script:
            - pipe: atlassian/firebase-deploy:0.2.1
              variables:
                FIREBASE_TOKEN: $FIREBASE_TOKEN_DEV
                PROJECT_ID: $FIREBASE_PROJECT