export const environment = {
  production: true,
  addThisScript: '//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-5ed48a5fc8315a5b',
  authService: 'https://us-central1-my-trending-stories-66f81.cloudfunctions.net/api/token/migration',
  isAnonymousUserEnabled: true,
  captchaKey: '6LfMnKoZAAAAALeLCs7H9LL9MhOy3EmcwtchxUf-',
  baseAPIDomain: 'https://us-central1-my-trending-stories-66f81.cloudfunctions.net',
  algolia: {
    applicationId: 'N7WFUORZZU',
    apiKey: '6f5d2e637debb45f0078b85091532c42',
    index: {
      fullSearch: 'prod_fullsearch_',
      companies: 'prod_companies_',
      charities: 'prod_charities_',
      fundraisers: 'prod_fundraisers_',
      textArticles: 'prod_text_articles_',
      audioArticles: 'prod_audio_article_',
      videoArticles: 'prod_video_article_',
      bloggers: 'prod_bloggers_',
      vloggers: 'prod_vloggers_',
      podcasters: 'prod_podcasters_',
      guestposters: 'prod_guestposters_',
      advisors: 'prod_advisors_',
      politicians: 'prod_politicians_',
      ecommerce: 'prod_ecommerce_',
      online_course: 'prod_online_course_',
      services: 'prod_services_',
      jobs: 'prod_jobs_',
      host_event: 'prod_host_events_',
      influencer_marketing: 'prod_influencer_marketing_',
      paid_premium_groups: 'prod_paid_premium_groups_',
      restaurants: 'prod_restaurants_',
      investments: 'prod_investments_',
      vacations_rentals: 'prod_vacations_rentals_',
    },
  },
  facebook: {
    appId: '327118671669396',
    version: 'v9.0'
  },
  firebase: {
    apiKey: 'AIzaSyBrkchwLnuHo6bqJzCYpENfSrg7Hfg2cDM',
    authDomain: 'my-trending-stories-66f81.firebaseapp.com',
    databaseURL: 'https://my-trending-stories-66f81.firebaseio.com',
    projectId: 'my-trending-stories-66f81',
    storageBucket: 'my-trending-stories-66f81.appspot.com',
    messagingSenderId: '172964785852',
    appId: '1:172964785852:web:2a5e84ca7c87db14cfeab9',
    measurementId: 'G-HWMGQKQ8F1'
  },
  storeUrl: 'https://store.mytrendingstories.com',
  stripePublishableKey: 'pk_live_5kBdKo0mxCY6HVt08s34GF9Z00hqJXEhDc',
  showAds: {
    onCompanyPage: false,
    onCharityPage: false,
    onFundraiserPage: false,
    onArticlePage: false,
    onCategoryPage: false,
    onHomePage: false
  },
  consoleURL: 'https://console.mytrendingstories.com',
};
